// Generated by tools/gen_plugin_params.py from plugin/params.json.
// Do not edit by hand; run the exporter + generator instead.
#pragma once

namespace snakeoil {

enum class ParamKind { Continuous, Toggle, Choice };

struct ParamSpec {
    const char* id;
    const char* label;
    const char* group;
    ParamKind kind;
    float minimum;
    float maximum;
    bool logarithmic;
    const char* choices;  // '|'-separated, or nullptr
    float defaultValue;   // choice: index; toggle: 0/1; continuous: value
};

inline const ParamSpec* paramSpecs(int& count) {
    static const ParamSpec kSpecs[] = {
    {"osc1_level", "Level", "Oscillator 1", ParamKind::Continuous, 0.0f, 1.0f, false, nullptr, 1.0f},
    {"osc1_square", "Square layer", "Oscillator 1", ParamKind::Toggle, 0.0f, 1.0f, false, nullptr, 1.0f},
    {"osc1_square_level", "Sq Level", "Oscillator 1", ParamKind::Continuous, 0.0f, 1.0f, false, nullptr, 0.5f},
    {"osc1_pwm", "PWM", "Oscillator 1", ParamKind::Continuous, 0.0f, 0.5f, false, nullptr, 0.0f},
    {"osc1_octave", "Octave down", "Oscillator 1", ParamKind::Toggle, 0.0f, 1.0f, false, nullptr, 0.0f},
    {"osc2_level", "Level", "Oscillator 2", ParamKind::Continuous, 0.0f, 1.0f, false, nullptr, 0.0f},
    {"detune2_semitones", "Coarse", "Oscillator 2", ParamKind::Continuous, -12.0f, 12.0f, false, nullptr, 0.0f},
    {"detune2_cents", "Fine", "Oscillator 2", ParamKind::Continuous, -0.5f, 0.5f, false, nullptr, 0.0f},
    {"osc2_pwm", "PWM", "Oscillator 2", ParamKind::Continuous, 0.0f, 0.5f, false, nullptr, 0.0f},
    {"osc2_octave", "Octave up", "Oscillator 2", ParamKind::Toggle, 0.0f, 1.0f, false, nullptr, 1.0f},
    {"mod_mode", "Mode", "Modulation", ParamKind::Choice, 0.0f, 1.0f, false, "off|fm|am|ring|sync", 1.0f},
    {"fm_depth", "Amount", "Modulation", ParamKind::Continuous, 0.0f, 1.0f, false, nullptr, 0.0f},
    {"lpf_cutoff", "Cutoff", "Filter", ParamKind::Continuous, 20.0f, 20000.0f, true, nullptr, 2000.0f},
    {"lpf_resonance", "Resonance", "Filter", ParamKind::Continuous, 0.0f, 1.0f, false, nullptr, 0.0f},
    {"lpf_slope", "Slope", "Filter", ParamKind::Choice, 0.0f, 1.0f, false, "12 dB|24 dB", 0.0f},
    {"lpf_master", "Master-bus filter", "Filter", ParamKind::Toggle, 0.0f, 1.0f, false, nullptr, 0.0f},
    {"flt_env_amount", "Env Amt", "Filter", ParamKind::Continuous, -1.0f, 1.0f, false, nullptr, 0.0f},
    {"flt_keytrack", "Key Trk", "Filter", ParamKind::Continuous, 0.0f, 1.0f, false, nullptr, 0.0f},
    {"flt_vel", "Vel>Cut", "Filter", ParamKind::Continuous, 0.0f, 1.0f, false, nullptr, 0.0f},
    {"master_gain", "Volume", "Master", ParamKind::Continuous, 0.0f, 1.2f, false, nullptr, 0.8f},
    {"velocity_on", "Velocity", "Master", ParamKind::Toggle, 0.0f, 1.0f, false, nullptr, 1.0f},
    {"auto_limiter", "Auto Limiter", "Master", ParamKind::Toggle, 0.0f, 1.0f, false, nullptr, 0.0f},
    {"amp_attack", "Attack", "Amp Envelope", ParamKind::Continuous, 0.001f, 5.0f, true, nullptr, 0.006f},
    {"amp_decay", "Decay", "Amp Envelope", ParamKind::Continuous, 0.001f, 5.0f, true, nullptr, 0.12f},
    {"amp_sustain", "Sustain", "Amp Envelope", ParamKind::Continuous, 0.0f, 1.0f, false, nullptr, 0.75f},
    {"amp_release", "Release", "Amp Envelope", ParamKind::Continuous, 0.001f, 10.0f, true, nullptr, 0.18f},
    {"flt_attack", "Attack", "Filter Env", ParamKind::Continuous, 0.001f, 5.0f, true, nullptr, 0.005f},
    {"flt_decay", "Decay", "Filter Env", ParamKind::Continuous, 0.001f, 5.0f, true, nullptr, 0.3f},
    {"flt_sustain", "Sustain", "Filter Env", ParamKind::Continuous, 0.0f, 1.0f, false, nullptr, 0.3f},
    {"flt_release", "Release", "Filter Env", ParamKind::Continuous, 0.001f, 10.0f, true, nullptr, 0.3f},
    {"lfo_rate", "Rate", "LFO 1", ParamKind::Continuous, 0.05f, 20.0f, true, nullptr, 5.0f},
    {"lfo_depth", "Depth", "LFO 1", ParamKind::Continuous, 0.0f, 1.0f, false, nullptr, 0.0f},
    {"lfo_wave", "Wave", "LFO 1", ParamKind::Choice, 0.0f, 1.0f, false, "sine|triangle|saw|square|random|random-glide", 0.0f},
    {"lfo_dest", "Dest", "LFO 1", ParamKind::Choice, 0.0f, 1.0f, false, "pitch|filter|pwm|amp|lfo2-rate", 0.0f},
    {"lfo2_rate", "Rate", "LFO 2", ParamKind::Continuous, 0.05f, 20.0f, true, nullptr, 5.0f},
    {"lfo2_depth", "Depth", "LFO 2", ParamKind::Continuous, 0.0f, 1.0f, false, nullptr, 0.0f},
    {"lfo2_wave", "Wave", "LFO 2", ParamKind::Choice, 0.0f, 1.0f, false, "sine|triangle|saw|square|random|random-glide", 0.0f},
    {"lfo2_dest", "Dest", "LFO 2", ParamKind::Choice, 0.0f, 1.0f, false, "pitch|filter|pwm|amp|lfo1-rate", 1.0f},
    {"glide_time", "Time", "Glide", ParamKind::Continuous, 0.0f, 2.0f, false, nullptr, 0.0f},
    {"glide_legato", "Legato only", "Glide", ParamKind::Toggle, 0.0f, 1.0f, false, nullptr, 0.0f},
    {"unison_voices", "Voices", "Unison", ParamKind::Choice, 0.0f, 1.0f, false, "1|2|3|4|5|6|7|8|9|10|11|12", 0.0f},
    {"unison_detune", "Detune", "Unison", ParamKind::Continuous, 0.0f, 50.0f, false, nullptr, 15.0f},
    {"unison_spread", "Spread", "Unison", ParamKind::Continuous, 0.0f, 1.0f, false, nullptr, 0.5f},
    {"noise_level", "Level", "Noise", ParamKind::Continuous, 0.0f, 1.0f, false, nullptr, 0.0f},
    {"noise_color", "Color", "Noise", ParamKind::Choice, 0.0f, 1.0f, false, "white|pink|brown", 0.0f},
    {"tempo_bpm", "BPM", "Tempo", ParamKind::Continuous, 40.0f, 240.0f, false, nullptr, 120.0f},
    {"mod1_src", "Source", "Mod Matrix", ParamKind::Choice, 0.0f, 1.0f, false, "none|Note Number|LFO 1|LFO 2|Mod Wheel|Aftertouch", 0.0f},
    {"mod1_amt", "Scale", "Mod Matrix", ParamKind::Continuous, -1.0f, 1.0f, false, nullptr, 0.0f},
    {"mod1_dst", "Destination", "Mod Matrix", ParamKind::Choice, 0.0f, 1.0f, false, "none|Osc 1: Level|Osc 1: PWM|Osc 1: Sq Level|Osc 2: Level|Osc 2: Tune|Osc 2: Fine|Osc 2: PWM|Noise: Level|Modulation Amount|Tempo|Filter: Cutoff|Filter: Resonance|Filter: Env Amount|Filter: Key Trk|Filter: Vel>Cut|Filter Env: Attack|Filter Env: Decay|Filter Env: Sustain|Filter Env: Release|Amp Env: Attack|Amp Env: Decay|Amp Env: Sustain|Amp Env: Release|Chorus: Depth|Delay: Time|Delay: Feedback|Delay: Tone|Reverb: Amount|Reverb: Size|Reverb: Damping|Bitcrush: Crush|Unison: Detune|Unison: Spread", 0.0f},
    {"mod2_src", "Source", "Mod Matrix", ParamKind::Choice, 0.0f, 1.0f, false, "none|Note Number|LFO 1|LFO 2|Mod Wheel|Aftertouch", 0.0f},
    {"mod2_amt", "Scale", "Mod Matrix", ParamKind::Continuous, -1.0f, 1.0f, false, nullptr, 0.0f},
    {"mod2_dst", "Destination", "Mod Matrix", ParamKind::Choice, 0.0f, 1.0f, false, "none|Osc 1: Level|Osc 1: PWM|Osc 1: Sq Level|Osc 2: Level|Osc 2: Tune|Osc 2: Fine|Osc 2: PWM|Noise: Level|Modulation Amount|Tempo|Filter: Cutoff|Filter: Resonance|Filter: Env Amount|Filter: Key Trk|Filter: Vel>Cut|Filter Env: Attack|Filter Env: Decay|Filter Env: Sustain|Filter Env: Release|Amp Env: Attack|Amp Env: Decay|Amp Env: Sustain|Amp Env: Release|Chorus: Depth|Delay: Time|Delay: Feedback|Delay: Tone|Reverb: Amount|Reverb: Size|Reverb: Damping|Bitcrush: Crush|Unison: Detune|Unison: Spread", 0.0f},
    {"mod3_src", "Source", "Mod Matrix", ParamKind::Choice, 0.0f, 1.0f, false, "none|Note Number|LFO 1|LFO 2|Mod Wheel|Aftertouch", 0.0f},
    {"mod3_amt", "Scale", "Mod Matrix", ParamKind::Continuous, -1.0f, 1.0f, false, nullptr, 0.0f},
    {"mod3_dst", "Destination", "Mod Matrix", ParamKind::Choice, 0.0f, 1.0f, false, "none|Osc 1: Level|Osc 1: PWM|Osc 1: Sq Level|Osc 2: Level|Osc 2: Tune|Osc 2: Fine|Osc 2: PWM|Noise: Level|Modulation Amount|Tempo|Filter: Cutoff|Filter: Resonance|Filter: Env Amount|Filter: Key Trk|Filter: Vel>Cut|Filter Env: Attack|Filter Env: Decay|Filter Env: Sustain|Filter Env: Release|Amp Env: Attack|Amp Env: Decay|Amp Env: Sustain|Amp Env: Release|Chorus: Depth|Delay: Time|Delay: Feedback|Delay: Tone|Reverb: Amount|Reverb: Size|Reverb: Damping|Bitcrush: Crush|Unison: Detune|Unison: Spread", 0.0f},
    {"mod4_src", "Source", "Mod Matrix", ParamKind::Choice, 0.0f, 1.0f, false, "none|Note Number|LFO 1|LFO 2|Mod Wheel|Aftertouch", 0.0f},
    {"mod4_amt", "Scale", "Mod Matrix", ParamKind::Continuous, -1.0f, 1.0f, false, nullptr, 0.0f},
    {"mod4_dst", "Destination", "Mod Matrix", ParamKind::Choice, 0.0f, 1.0f, false, "none|Osc 1: Level|Osc 1: PWM|Osc 1: Sq Level|Osc 2: Level|Osc 2: Tune|Osc 2: Fine|Osc 2: PWM|Noise: Level|Modulation Amount|Tempo|Filter: Cutoff|Filter: Resonance|Filter: Env Amount|Filter: Key Trk|Filter: Vel>Cut|Filter Env: Attack|Filter Env: Decay|Filter Env: Sustain|Filter Env: Release|Amp Env: Attack|Amp Env: Decay|Amp Env: Sustain|Amp Env: Release|Chorus: Depth|Delay: Time|Delay: Feedback|Delay: Tone|Reverb: Amount|Reverb: Size|Reverb: Damping|Bitcrush: Crush|Unison: Detune|Unison: Spread", 0.0f},
    {"mod5_src", "Source", "Mod Matrix", ParamKind::Choice, 0.0f, 1.0f, false, "none|Note Number|LFO 1|LFO 2|Mod Wheel|Aftertouch", 0.0f},
    {"mod5_amt", "Scale", "Mod Matrix", ParamKind::Continuous, -1.0f, 1.0f, false, nullptr, 0.0f},
    {"mod5_dst", "Destination", "Mod Matrix", ParamKind::Choice, 0.0f, 1.0f, false, "none|Osc 1: Level|Osc 1: PWM|Osc 1: Sq Level|Osc 2: Level|Osc 2: Tune|Osc 2: Fine|Osc 2: PWM|Noise: Level|Modulation Amount|Tempo|Filter: Cutoff|Filter: Resonance|Filter: Env Amount|Filter: Key Trk|Filter: Vel>Cut|Filter Env: Attack|Filter Env: Decay|Filter Env: Sustain|Filter Env: Release|Amp Env: Attack|Amp Env: Decay|Amp Env: Sustain|Amp Env: Release|Chorus: Depth|Delay: Time|Delay: Feedback|Delay: Tone|Reverb: Amount|Reverb: Size|Reverb: Damping|Bitcrush: Crush|Unison: Detune|Unison: Spread", 0.0f},
    {"mod6_src", "Source", "Mod Matrix", ParamKind::Choice, 0.0f, 1.0f, false, "none|Note Number|LFO 1|LFO 2|Mod Wheel|Aftertouch", 0.0f},
    {"mod6_amt", "Scale", "Mod Matrix", ParamKind::Continuous, -1.0f, 1.0f, false, nullptr, 0.0f},
    {"mod6_dst", "Destination", "Mod Matrix", ParamKind::Choice, 0.0f, 1.0f, false, "none|Osc 1: Level|Osc 1: PWM|Osc 1: Sq Level|Osc 2: Level|Osc 2: Tune|Osc 2: Fine|Osc 2: PWM|Noise: Level|Modulation Amount|Tempo|Filter: Cutoff|Filter: Resonance|Filter: Env Amount|Filter: Key Trk|Filter: Vel>Cut|Filter Env: Attack|Filter Env: Decay|Filter Env: Sustain|Filter Env: Release|Amp Env: Attack|Amp Env: Decay|Amp Env: Sustain|Amp Env: Release|Chorus: Depth|Delay: Time|Delay: Feedback|Delay: Tone|Reverb: Amount|Reverb: Size|Reverb: Damping|Bitcrush: Crush|Unison: Detune|Unison: Spread", 0.0f},
    {"mod7_src", "Source", "Mod Matrix", ParamKind::Choice, 0.0f, 1.0f, false, "none|Note Number|LFO 1|LFO 2|Mod Wheel|Aftertouch", 0.0f},
    {"mod7_amt", "Scale", "Mod Matrix", ParamKind::Continuous, -1.0f, 1.0f, false, nullptr, 0.0f},
    {"mod7_dst", "Destination", "Mod Matrix", ParamKind::Choice, 0.0f, 1.0f, false, "none|Osc 1: Level|Osc 1: PWM|Osc 1: Sq Level|Osc 2: Level|Osc 2: Tune|Osc 2: Fine|Osc 2: PWM|Noise: Level|Modulation Amount|Tempo|Filter: Cutoff|Filter: Resonance|Filter: Env Amount|Filter: Key Trk|Filter: Vel>Cut|Filter Env: Attack|Filter Env: Decay|Filter Env: Sustain|Filter Env: Release|Amp Env: Attack|Amp Env: Decay|Amp Env: Sustain|Amp Env: Release|Chorus: Depth|Delay: Time|Delay: Feedback|Delay: Tone|Reverb: Amount|Reverb: Size|Reverb: Damping|Bitcrush: Crush|Unison: Detune|Unison: Spread", 0.0f},
    {"mod8_src", "Source", "Mod Matrix", ParamKind::Choice, 0.0f, 1.0f, false, "none|Note Number|LFO 1|LFO 2|Mod Wheel|Aftertouch", 0.0f},
    {"mod8_amt", "Scale", "Mod Matrix", ParamKind::Continuous, -1.0f, 1.0f, false, nullptr, 0.0f},
    {"mod8_dst", "Destination", "Mod Matrix", ParamKind::Choice, 0.0f, 1.0f, false, "none|Osc 1: Level|Osc 1: PWM|Osc 1: Sq Level|Osc 2: Level|Osc 2: Tune|Osc 2: Fine|Osc 2: PWM|Noise: Level|Modulation Amount|Tempo|Filter: Cutoff|Filter: Resonance|Filter: Env Amount|Filter: Key Trk|Filter: Vel>Cut|Filter Env: Attack|Filter Env: Decay|Filter Env: Sustain|Filter Env: Release|Amp Env: Attack|Amp Env: Decay|Amp Env: Sustain|Amp Env: Release|Chorus: Depth|Delay: Time|Delay: Feedback|Delay: Tone|Reverb: Amount|Reverb: Size|Reverb: Damping|Bitcrush: Crush|Unison: Detune|Unison: Spread", 0.0f},
    {"fx_chorus", "Chorus", "Effects", ParamKind::Toggle, 0.0f, 1.0f, false, nullptr, 0.0f},
    {"fx_chorus_depth", "Depth", "Effects", ParamKind::Continuous, 0.0f, 1.0f, false, nullptr, 0.3f},
    {"fx_delay", "Delay", "Effects", ParamKind::Toggle, 0.0f, 1.0f, false, nullptr, 0.0f},
    {"fx_delay_time", "Time", "Effects", ParamKind::Continuous, 200.0f, 4000.0f, true, nullptr, 300.0f},
    {"fx_delay_pingpong", "Ping-pong", "Effects", ParamKind::Toggle, 0.0f, 1.0f, false, nullptr, 0.0f},
    {"fx_delay_feedback", "Feedback", "Effects", ParamKind::Continuous, 0.0f, 0.95f, false, nullptr, 0.35f},
    {"fx_delay_damp", "Tone", "Effects", ParamKind::Continuous, 0.0f, 0.9f, false, nullptr, 0.25f},
    {"fx_delay_sync", "Sync", "Effects", ParamKind::Toggle, 0.0f, 1.0f, false, nullptr, 0.0f},
    {"fx_delay_division", "Division", "Effects", ParamKind::Choice, 0.0f, 1.0f, false, "1/1|1/2|1/2.|1/4|1/4.|1/4T|1/8|1/8.|1/8T|1/16|1/16.", 6.0f},
    {"fx_reverb", "Reverb", "Effects", ParamKind::Toggle, 0.0f, 1.0f, false, nullptr, 0.0f},
    {"fx_reverb_amount", "Amount", "Effects", ParamKind::Continuous, 0.0f, 1.0f, false, nullptr, 0.3f},
    {"fx_reverb_size", "Size", "Effects", ParamKind::Continuous, 0.5f, 0.98f, false, nullptr, 0.84f},
    {"fx_reverb_damp", "Damping", "Effects", ParamKind::Continuous, 0.0f, 0.9f, false, nullptr, 0.25f},
    {"fx_bitcrush", "Bitcrush", "Effects", ParamKind::Toggle, 0.0f, 1.0f, false, nullptr, 0.0f},
    {"fx_bitcrush_amount", "Crush", "Effects", ParamKind::Continuous, 0.0f, 1.0f, false, nullptr, 0.5f},
    };
    count = static_cast<int>(sizeof(kSpecs) / sizeof(kSpecs[0]));
    return kSpecs;
}

}  // namespace snakeoil
