"""Generate plugin/src/params_gen.hpp from plugin/params.json.

The spec table is JUCE-free so both the DSP and the JUCE wrapper can use it: the
processor builds its AudioProcessorValueTreeState layout from it, and the engine
maps parameter ids to DSP state. Regenerate after the registry changes:

    python tools/export_params.py && python tools/gen_plugin_params.py
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARAMS = os.path.join(ROOT, "plugin", "params.json")
OUT = os.path.join(ROOT, "plugin", "src", "params_gen.hpp")

SEP = "|"


def kind_enum(kind):
    return {"continuous": "ParamKind::Continuous",
            "toggle": "ParamKind::Toggle",
            "choice": "ParamKind::Choice"}[kind]


def c_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def spec_lines(params):
    lines = []
    for p in params:
        choices = SEP.join(p["choices"])
        default = p["default"]
        if p["kind"] == "choice":
            default_value = p["choices"].index(default) if default in p["choices"] else 0
        elif p["kind"] == "toggle":
            default_value = 1 if default else 0
        else:
            default_value = float(default)
        lines.append(
            "    {%s, %s, %s, %s, %sf, %sf, %s, %s, %sf, %s}," % (
                c_string(p["id"]), c_string(p["label"]), c_string(p["group"]),
                kind_enum(p["kind"]), repr(float(p["minimum"])), repr(float(p["maximum"])),
                "true" if p["scale"] == "log" else "false",
                c_string(choices) if choices else "nullptr",
                repr(float(default_value)),
                c_string(p.get("under", "")),
            )
        )
    return lines


def main():
    with open(PARAMS, encoding="utf-8") as handle:
        payload = json.load(handle)
    params = payload["params"]
    body = "\n".join(spec_lines(params))
    text = f"""// Generated by tools/gen_plugin_params.py from plugin/params.json.
// Do not edit by hand; run the exporter + generator instead.
#pragma once

namespace snakeoil {{

enum class ParamKind {{ Continuous, Toggle, Choice }};

struct ParamSpec {{
    const char* id;
    const char* label;
    const char* group;
    ParamKind kind;
    float minimum;
    float maximum;
    bool logarithmic;
    const char* choices;  // '{SEP}'-separated, or nullptr
    float defaultValue;   // choice: index; toggle: 0/1; continuous: value
    const char* under;    // id of the control this one depends on ("" when none)
}};

inline const ParamSpec* paramSpecs(int& count) {{
    static const ParamSpec kSpecs[] = {{
{body}
    }};
    count = static_cast<int>(sizeof(kSpecs) / sizeof(kSpecs[0]));
    return kSpecs;
}}

}}  // namespace snakeoil
"""
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write(text)
    print("wrote %s (%d params)" % (OUT, len(params)))


if __name__ == "__main__":
    main()
